// Generated by CoffeeScript 1.6.2
(function() {
  var UniqueSet;

  UniqueSet = require('../utils/unique_set').UniqueSet;

  module.exports = {
    user: new UniqueSet,
    channel: new UniqueSet
  };

}).call(this);
