// Generated by CoffeeScript 1.6.2
var fs;

fs = require('fs');

module.exports = function(responderId, config, ss) {
  var name;

  name = config && config.name || 'events';
  return {
    name: name,
    interfaces: function(middleware) {
      return {
        websocket: function(msg, meta, send) {
          return send(JSON.stringify(msg));
        }
      };
    }
  };
};
